# Generated by Django 3.0.4 on 2020-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180607_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='is_employable',
            field=models.TextField(default=False),
        ),
    ]
