# Generated by Django 3.0.4 on 2020-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200428_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='is_employable',
            field=models.TextField(),
        ),
    ]
