# Generated by Django 3.0.4 on 2020-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200428_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='is_employable',
            field=models.TextField(),
        ),
    ]
