# Generated by Django 3.0.4 on 2020-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200428_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='is_employable',
            field=models.CharField(max_length=50),
        ),
    ]
